name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions-Windows:
    runs-on: windows-2022
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: python --version
      - name: Install python packages
        run: python -m pip install -r requirements.txt
      - name: Execute python script
        run: python src\sample.py
      - name: Test with pytest
        run: |
          pytest --junitxml=junit/test-results.xml
      - name: Create package
        run: pyinstaller src\sample.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  Explore-GitHub-Actions-Linux:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: python --version
      - name: Install python packages
        run: python -m pip install -r requirements.txt
      - name: Execute python script
        run: python src\sample.py
      - name: Create package
        run: pyinstaller src\sample.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
